version: '2.3'
services:
  bookstore-mysql:
    image: "mysql:5.6"
    container_name: bookstore-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      bookstore:
    ports:
    - 3306:3306
    volumes:
    - type: volume
      source: bookstore-mysql-volume
      target: /var/lib/mysql
  bookstore-adminer:
    image: "adminer"
    container_name: bookstore-adminer
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      bookstore:
    ports:
    - 8086:8080
  bookstore-backend:
    image: "uni-bookstore"
    build:
      context: .
    container_name: bookstore-backend
    networks:
      bookstore:
    ports:
    - 8085:8085
    depends_on:
      - bookstore-mysql
networks:
  bookstore:
    driver: bridge
volumes:
  bookstore-mysql-volume:
